name: Update chile.json

on:
  push:
    branches: master
    paths: minciencia_data/*.csv

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Organize data
        run: |
          python data_organizer.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          base: master
          branch: update-chile-json
          commit-message: 'feat(chile): update json'
          committer: Javier López <javierlopez@uc.cl>
          title: Update chile.json
          body: A data csv file was updated. Therefore, we update chile.json.
          author: Javier López <javierlopez@uc.cl>
