name: Check for new reporte diario

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get last reporte diario data
        run: |
          cd reporte_parser
          python reporte_parser.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          base: master
          branch: reporte-diario-update
          commit-message: 'feat: update data from reporte diario'
          committer: Javier López <javierlopez@uc.cl>
          title: 'New reporte diario data update'
          body: A new reporte diario was published. Therefore, we update our data.
          author: Javier López <javierlopez@uc.cl>
