name: Check for new reporte diario

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check for new reporte diario
        id: reporte_check
        run: |
          cd reporte_checker
          python reporte_checker.py
        continue-on-error: true

      - name: Create Issue
        if: ${{ steps.reporte_check.outcome == 'success' }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/NEW_REPORTE_ISSUE.md
